crt0.o: crt0.asm
	nasm -f elf -g crt0.asm -o crt0.o

%.o: %.c
	$(CC) $(MAKE_CFLAGS) -D "__INLIBC" -o $@ -c $<

%-asm.o: %.asm
	$(AS) -f elf -g -o $@ $(ASFLAGS) $<

.PHONY: clean
clean:
	find -L src -type f -iregex "^.*\.o" | xargs rm -f
	rm crt0.o
	rm libstdc.a
