all: libstdc.a

CC := gcc
LD := ld
AS := nasm

MAKE_CFLAGS = -O2 -frecord-gcc-switches -g -std=gnu99 -Wall -Werror -m32 -I include -I src -ffreestanding -fno-stack-protector -nostdinc -masm=intel -pipe -Wno-unused-but-set-variable
MAKE_CFLAGS += $(CFLAGS)
