base_dependencies:
  - base
env:
  ac_cv_func_calloc_0_nonnull: 'yes'
  ac_cv_func_chown_works: 'yes'
  ac_cv_func_getgroups_works: 'yes'
  ac_cv_func_malloc_0_nonnull: 'yes'
  gl_cv_func_cbrtl_ieee: 'yes'
  gl_cv_func_ceilf_ieee: 'yes'
  gl_cv_func_ceil_ieee: 'yes'
  gl_cv_func_ceill_ieee: 'yes'
  gl_cv_func_chown_ctime_works: 'yes'
  gl_cv_func_chown_slash_works: 'yes'
  gl_cv_func_exp2l_ieee: 'yes'
  gl_cv_func_expm1_ieee: 'yes'
  gl_cv_func_fcntl_f_dupfd_works: 'yes'
  gl_cv_func_fdopendir_works: 'yes'
  gl_cv_func_floorf_ieee: 'yes'
  gl_cv_func_fmaf_works: 'yes'
  gl_cv_func_fmal_works: 'yes'
  gl_cv_func_fma_works: 'yes'
  gl_cv_func_fmodf_ieee: 'yes'
  gl_cv_func_fmod_ieee: 'yes'
  gl_cv_func_fmodl_ieee: 'yes'
  gl_cv_func_fpurge_works: 'yes'
  gl_cv_func_futimens_works: 'yes'
  gl_cv_func_futimesat_works: 'yes'
  gl_cv_func_getgroups_works: 'yes'
  gl_cv_func_gettimeofday_clobber: 'no'
  gl_cv_func_hypotf_ieee: 'yes'
  gl_cv_func_hypotl_ieee: 'yes'
  gl_cv_func_hypot_ieee: 'yes'
  gl_cv_func_isfinitel_works: 'yes'
  gl_cv_func_isnanl_works: 'yes'
  gl_cv_func_log10f_ieee: 'yes'
  gl_cv_func_log10_ieee: 'yes'
  gl_cv_func_log1pf_ieee: 'yes'
  gl_cv_func_log1p_ieee: 'yes'
  gl_cv_func_log1pl_ieee: 'yes'
  gl_cv_func_log2f_ieee: 'yes'
  gl_cv_func_log2_ieee: 'yes'
  gl_cv_func_logf_ieee: 'yes'
  gl_cv_func_log_ieee: 'yes'
  gl_cv_func_lstat_dereferences_slashed_symlink: 'yes'
  gl_cv_func_mbrlen_empty_input: 'yes'
  gl_cv_func_mbrtowc_empty_input: 'yes'
  gl_cv_func_memchr_works: 'yes'
  gl_cv_func_memmem_works_fast: 'yes'
  gl_cv_func_mkdir_trailing_dot_works: 'yes'
  gl_cv_func_mkdir_trailing_slash_works: 'yes'
  gl_cv_func_mkfifo_works: 'yes'
  gl_cv_func_mknod_works: 'yes'
  gl_cv_func_modff_ieee: 'yes'
  gl_cv_func_modf_ieee: 'yes'
  gl_cv_func_modfl_ieee: 'yes'
  gl_cv_func_nanosleep: 'yes'
  gl_cv_func_open_directory_works: 'yes'
  gl_cv_func_perror_works: 'yes'
  gl_cv_func_printf_directive_a: 'yes'
  gl_cv_func_printf_directive_f: 'yes'
  gl_cv_func_printf_directive_n: 'yes'
  gl_cv_func_printf_enomem: 'yes'
  gl_cv_func_printf_flag_zero: 'yes'
  gl_cv_func_printf_infinite_long_double: 'yes'
  gl_cv_func_printf_infinite: 'yes'
  gl_cv_func_printf_sizes_c99: 'yes'
  gl_cv_func_pselect_detects_ebadf: 'yes'
  gl_cv_func_ptsname_sets_errno: 'yes'
  gl_cv_func_readlink_works: 'yes'
  gl_cv_func_realpath_works: 'yes'
  gl_cv_func_remainderf_ieee: 'yes'
  gl_cv_func_remainder_ieee: 'yes'
  gl_cv_func_remainderl_ieee: 'yes'
  gl_cv_func_rename_dest_works: 'yes'
  gl_cv_func_rename_link_works: 'yes'
  gl_cv_func_rename_slash_dst_works: 'yes'
  gl_cv_func_rename_slash_src_works: 'yes'
  gl_cv_func_rmdir_works: 'yes'
  gl_cv_func_roundf_ieee: 'yes'
  gl_cv_func_round_ieee: 'yes'
  gl_cv_func_select_detects_ebadf: 'yes'
  gl_cv_func_setenv_works: 'yes'
  gl_cv_func_signbit_gcc: 'yes'
  gl_cv_func_signbit: 'yes'
  gl_cv_func_snprintf_directive_n: 'yes'
  gl_cv_func_snprintf_retval_c99: 'yes'
  gl_cv_func_snprintf_truncation_c99: 'yes'
  gl_cv_func_stat_dir_slash: 'yes'
  gl_cv_func_stat_file_slash: 'yes'
  gl_cv_func_stpncpy: 'yes'
  gl_cv_func_strcasestr_linear: 'yes'
  gl_cv_func_strchrnul_works: 'yes'
  gl_cv_func_strerror_0_works: 'yes'
  gl_cv_func_strstr_linear: 'yes'
  gl_cv_func_strtod_works: 'yes'
  gl_cv_func_svid_putenv: 'yes'
  gl_cv_func_symlink_works: 'yes'
  gl_cv_func_tdelete_works: 'yes'
  gl_cv_func_truncf_ieee: 'yes'
  gl_cv_func_trunc_ieee: 'yes'
  gl_cv_func_truncl_ieee: 'yes'
  gl_cv_func_tzset_clobber: 'no'
  gl_cv_func_ungetc_works: 'yes'
  gl_cv_func_unlink_honors_slashes: 'yes'
  gl_cv_func_unsetenv_works: 'yes'
  gl_cv_func_usleep_works: 'yes'
  gl_cv_func_utimensat_works: 'yes'
  gl_cv_func_vsnprintf_posix: 'yes'
  gl_cv_func_vsnprintf_zerosize_c99: 'yes'
  gl_cv_func_vsprintf_posix: 'yes'
  gl_cv_func_wcwidth_works: 'yes'
  gl_cv_func_working_getdelim: 'yes'
  gl_cv_func_working_mkstemp: 'yes'
  gl_cv_func_working_mktime: 'yes'
  gl_cv_func_working_strerror: 'yes'
  #- gl_cv_func_sleep_works: 'yes'
  #- gl_cv_func_linkat_slash: 'yes'
  #- gl_cv_func_link_works: 'yes'
  #- ac_cv_func___fseterr: 'yes'
  #- gl_cv_func_getcwd_null: 'yes'
  #- gl_cv_struct_dirent_d_ino: 'yes'
  #- ac_cv_func_realloc_0_nonnull: 'yes'
