CC=../toolchain/userspace/local/bin/i586-pc-xelix-gcc
LD=../toolchain/userspace/local/bin/i586-pc-xelix-ld
CFLAGS="-std=gnu99"

TARGETS=xinit xshell cat ls pwd cd

all: $(TARGETS)

clean:
	rm -f $(TARGETS)
