# This file has been generated by ./configure. You usually don't want to change it manually.\n
include Makefile.header
libstdc.a: src/stdio/print.o src/string/memset.o src/string/strlen.o src/string/memcpy.o src/unistd/execvp.o src/stdlib/exit.o
	ar rcs libstdc.a $^
	nasm -f elf -g crt0.asm -o crt0.o
src/stdio/print.c: include/stdio.h include/stddef.h include/stdint.h include/string.h
src/string/memset.c: include/stdint.h
src/string/strlen.c: include/stddef.h include/stdint.h include/string.h
src/string/memcpy.c: include/stdint.h
src/unistd/execvp.c: include/unistd.h include/stdio.h
src/stdlib/exit.c: include/stdlib.h
include Makefile.footer
