#!/usr/bin/env python
import shlex

def main():
	print('Reading common/stdconf.h...')
	f = open('common/stdconf.h')
	c = open('local.h', 'w')
	c.write('// Generated by tools/txtconfig.py\n')
	c.write('#pragma once\n')

	while True:
		i = f.readline()
		if not i:
			break
		if i.startswith('#'):
			command = shlex.split(i[1:-1])

			if command[0] == 'define' and len(command) == 3:
				now = raw_input('{0} [{1}]:'.format(command[1], command[2]))
				if not now or now == '':
					continue
				c.write('#undef {0}\n#define {0} {1}\n'.format(command[1], now))

			elif command[0] == 'define' and len(command) == 2:
				now = raw_input('{0} [Y/n]:'.format(command[1]))
				if not now or now in ('y', 'yes', 'Y', 'Yes', 'YES', ''):
					continue
				c.write('#undef {0}\n'.format(command[1]))

			elif command[0] == 'undef' and len(command) == 2:
				now = raw_input('{0} [y/N]:'.format(command[1]))

				if not now or now in ('n', 'no', 'N', 'No', 'NO', ''):
					continue
				c.write('#define {0}\n'.format(command[1]))
				
if __name__ == '__main__':
	main()
